### ISSUE TITLE
Feature Request: Items can be placed in world somehow and activating them gives you the information

### ISSUE THREAD

**Issue by Lothrazar** [Darkhax-Minecraft/Informational-Accessories#4]
You might not agree but hear me out.  I had this idea for the calendar and Sextant, it might not make sense with the others.

A player stops by his home base, wonders what date it is so taps the calendar on the wall and finds out.  Player does not want to carry it around all the time, and this is faster than taking it in/out of a bag.

If multi items support this, you could maybe do some pedestal block?

Optionally maybe with redstone, so i could ping it in the morning with a daylight sensor?

I picture something like "player.sendStatusMessage" so its not just a boring chat message?

**Comment by Darkhax** [comment]
This is a cool idea however after thinking about it a bit more and considering the original intent of this mod I don't really think it would be a good fit. Thanks for the suggestion though. Perhaps I may implement this idea in a future mod or maybe Dark Utilities.
