### ISSUE TITLE
[Bug] Info shows in JEI

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Informational-Accessories#5]
The tooltips that convey the information provided by the accessories is visible in JEI, completely removing the necessity of crafting them.

**Comment by Darkhax** [comment]
Thanks for the report. I will look into a fix for this.

**Comment by Darkhax** [comment]
Fixed by https://github.com/Darkhax-Minecraft/Informational-Accessories/commit/9de2cc0e13aac9bdcf220993b1f802592173d35a 

Can be downloaded [here](https://minecraft.curseforge.com/projects/informational-accessories/files/2516288) once reviewed by Curse.
