### ISSUE TITLE
Compass info showing improperly

### ISSUE THREAD

**Issue by tahg** [Darkhax-Minecraft/Informational-Accessories#7]
I only have the compass so far, so maybe other tools do this as well.  When moving off the compass item, the text gets rendered twice.
![compass](https://user-images.githubusercontent.com/499508/39405905-3fa98288-4b7c-11e8-8e2b-33b87699bde2.png)

EDIT: It seems to sometimes do this as well while keeping the compass selected, but I couldn't see any particular reason. (I was just standing still looking at a GUI)

**Comment by Darkhax** [comment]
The info text added by this mod is put in the f3 screen, and not above the hotbar. The compass also only shows the current x and y value, not altitude or chunk.

**Comment by tahg** [comment]
Ah, sorry about then.  That's the trouble with testing in a modpack. I'll just have to report this to the pack author, and hope they know which other mod adds this info.
