### ISSUE TITLE
Suggestion: add direction and inclination to compass

### ISSUE THREAD

**Issue by tahg** [Darkhax-Minecraft/Informational-Accessories#8]
The compass currently doesn't show anything you'd actually expect from it.  The things it shows are usually generally associated with a GPS device. It would be nice if it would show:

Precise and Rough Direction(yaw) - This is what you'd normally get from a compass. (Precise in my mind would be something like decimal degrees with say, 1/1000 of a degree precision. Rough would be something like one of N, NE, E, SE, S, SW, W, NW)

Precise Inclination(pitch) - Not really a feature of a function, but not that hard to make a real world device of the sort.  At any rate, it'd be the only thing missing from the player location/rotation, and I'm pretty sure the debug screen normally shows it.

**Comment by Darkhax** [comment]
This is a great feature idea, sorry it took me forever to add it. The code has been done for a while but got lost in my local repo. This feature was added in https://github.com/Darkhax-Minecraft/Informational-Accessories/commit/03493bd5fbe2f9231c205d6d6e801bdc63a6ff50
